### ISSUE TITLE
bwa workflow cannot self-test

### ISSUE THREAD

**Issue by denis-yuen** [SeqWare/public-workflows#33]
We ( @niall-byrne and I) ran into this issue. 
The bundle is now incapable of self-testing (seqware bundle launch --dir <workflow-dir>) since the bundled default ini is missing keys. 

    bwaAlignSlots
    bwaSampleSlots
    picardSortJobSlots
    uploadScriptJobSlots
    gtdownloadSlots
    smallJobSlots
    unmappedReadsJobMemSlots
    analysisCenter\

We surmise that the default values may be correct from the decider and are the following (not sure what to use for analysis center for self-testing)

    bwaAlignSlots=8
    bwaSampleSlots=8
    picardSortJobSlots=4
    uploadScriptJobSlots=4
    gtdownloadSlots=8
    smallJobSlots=2
    unmappedReadsJobMemSlots=4
    unmappedReadsJobSlots=4

**Comment by niall-byrne** [comment]
Fixed in develop.
